---
kind: pipeline
type: kubernetes
name: dockery

__dind_agent: &agent
  image: registry-np.storage-system.svc.k8s.local/orbs/dind:blue
  pull: always
  volumes:
    - name: dockersock
      path: /var/run
  environment:
    REGISTRY: registry-np.storage-system.svc.k8s.local

steps:
  - name: build-the-builder
    <<: *agent
    commands:
      - while ! curl -s --unix-socket /var/run/docker.sock http://localhost/; do sleep 1; done
      - make builder
  - name: docker-image
    <<: *agent
    commands:
      - make pull || (make docker && make push)
      - make push-head
  - name: mkdocs
    <<: *agent
    commands:
      - export BUILDER_VERSION=$(./docker/hacks/builder-version.sh)
      - ln -sf /getbetter.ro/galleries content/
      - ./hacks/cache-bust-extras.sh
      - make drone-mkdocs
  - name: preview
    when:
      branch:
        exclude:
          - main
    <<: *agent
    environment:
      MCONF:
        from_secret: minio-cli-config
    commands:
      - mkdir -p /tmp/mcli && echo $${MCONF} | base64 -d > /tmp/mcli/config.json
      - mcli --quiet --config-dir /tmp/mcli mirror --overwrite --md5 www/galleries/ local/getbetter-staging/galleries >/dev/null
      - mcli --quiet --config-dir /tmp/mcli mirror --overwrite --md5 www/images/ local/getbetter-staging/images >/dev/null
      - mcli --quiet --config-dir /tmp/mcli mirror --overwrite --md5 --remove --exclude "galleries/*" --exclude "images/*" www/ local/getbetter-staging/${DRONE_COMMIT_SHA:0:12}
      - echo 'Preview URL:' https://preview.getbetter.ro/${DRONE_COMMIT_SHA:0:12}/
  - name: deploy
    when:
      branch:
        - main
    <<: *agent
    commands:
      - make drone-sync

services:
  - name: docker-daemon
    <<: *agent
    privileged: true

volumes:
  - name: dockersock
    temp: {}
