site_name: Getbetter
site_description: Rareș' 2nd brain
strict: true
site_url: https://getbetter.ro/
copyright: |
  Copyright &copy; 2010 - 2023 <a href="https://github.com/rarescosma"  target="_blank" rel="noopener">Rareș Cosma</a>

theme:
  name: material
  logo: logo.svg
  favicon: favicon.png
  font: false
  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/moon-waxing-crescent
        name: Switch to dark mode

extra_css:
  - assets/stylesheets/gfonts.css
  - assets/stylesheets/macros.css
  - assets/stylesheets/popup.css
extra_javascript:
  - assets/javascripts/gallery.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rarescosma
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rarescosma

docs_dir: content
site_dir: www

markdown_extensions:
  - admonition
  - extra
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - markdown_include.include:
      base_path: content
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🔗

plugins:
  - awesome-pages
  - exclude:
      glob:
      - _build/*
      - build/*
  - git-revision-date
  - macros:
      module_name: "getbetter/macros"
  - minify:
      minify_html: true
  - search

validation:
  absolute_links: ignore
