site_name: getbetter
site_description: Rareș' 2nd brain
strict: true
site_url: https://getbetter.ro/

theme:
  name: 'material'
  palette:
    primary: indigo
    accent: indigo
  logo: 'logo.svg'
  favicon: 'favicon.png'
  features:
    - instant

repo_name: rarescosma/getbetter.ro
repo_url: https://github.com/rarescosma/getbetter.ro

extra_css:
  - extra/videobox.css
extra_javascript: []

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rarescosma
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rarescosma

docs_dir: content

nav:
  - About: index.md
  - journal.md
  - Climbing:
    - climbing/circuit_exercises.md
    - climbing/course.md
    - climbing/warmup.md
  - Ops:
    - ops/12_factor_apps.md
  - Learning:
    - learning/learning_to_learn.md
  - Linux:
    - linux/rsync_tricks.md
    - linux/running_old_packages_on_arch.md

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: content
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: 🔗

plugins:
  - search:
      prebuild_index: true
  - exclude:
      glob:
      - _build/*
      - build/*
  - macros
  - minify:
      minify_html: true
