site_name: Getbetter
site_description: Rareș' 2nd brain
strict: true
site_url: https://getbetter.ro/
copyright: |
  Copyright &copy; 2010 - 2024 <a href="https://github.com/rarescosma"  target="_blank" rel="noopener">Rareș Cosma</a>

theme:
  name: material
  logo: logo.svg
  favicon: favicon.png
  font: false
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - assets/stylesheets/gfonts.css
  - assets/stylesheets/macros.css
  - assets/stylesheets/popup.css
extra_javascript:
  - assets/javascripts/plausible.js
  - assets/javascripts/gallery.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rarescosma
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rarescosma

docs_dir: content
site_dir: www

markdown_extensions:
  - admonition
  - extra
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - markdown_include.include:
      base_path: content
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🔗

plugins:
  - awesome-pages
  - include_dir_to_nav:
      file_pattern: '^(?!index\.md$).*\.md$'
  - exclude:
      glob:
      - _build/*
      - build/*
  - git-revision-date
  - macros:
      module_name: "getbetter/macros"
  - minify:
      minify_html: true
  - search
  - exclude-search:
      exclude:
        - journal/*
        - archive/*

nav:
  - Home: index.md
  - Projects:
      - projects/index.md
      - projects
  - Tech articles: tech
  - Journal: journal
  - Archive: archive

validation:
  absolute_links: ignore
