ARG REGISTRY

FROM ${REGISTRY}/python:3.11.1

COPY pyproject.toml poetry.lock ./

RUN apt-get -qq update \
    && apt-get -qq install -y git make wget rsync imagemagick xz-utils \
    && pip install --no-cache-dir poetry \
    && rm -rf /var/lib/apt

RUN wget -qO- "https://github.com/watchexec/watchexec/releases/download/1.12.0/watchexec-1.12.0-x86_64-unknown-linux-gnu.tar.xz" \
  | tar -xJf - --strip-components 1 -C /tmp/ \
  && mv /tmp/watchexec /usr/bin

RUN POETRY_VIRTUALENVS_CREATE=false poetry install --without dev
