ARG REGISTRY

FROM ${REGISTRY}/python:3.11.1

COPY pyproject.toml poetry.lock ./

RUN apt-get -qq update \
    && apt-get -qq install -y git make wget rsync imagemagick xz-utils \
    && pip install --no-cache-dir poetry \
    && rm -rf /var/lib/apt

RUN POETRY_VIRTUALENVS_CREATE=false poetry install --without dev
